Prepare this data to model with multivariable regression (including data cleaning if necessary) according to this specification:

$$ Property crime = \alpha + Population + Population^2 + Murder + Robbery$$

The 'population' variable is already set for you, but you will need to create the last three features.  Robbery and Murder are currently continuous variables.  For this model, please use these variables to create  categorical features where values greater than 0 are coded 1, and values equal to 0 are coded 0.  You'll use this data and model in a later assignment- for now, just write the code you need to get the data ready.  Don't forget basic data cleaning procedures, either!  Do some graphing to see if there are any anomalous cases, and decide how you want to deal with them.

In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn import linear_model
%matplotlib inline

In [2]:
df = pd.read_excel('table_8_offenses_known_to_law_enforcement_new_york_by_city_2013.xls', header=4)
drop_df = df.drop('Rape\n(revised\ndefinition)1',axis=1) #removing column because only NaN values
crime_df = drop_df[:-3] #Last three rows are not data

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3
0,Adams Village,1861.0,0.0,0.0,0.0,0.0,0.0,12.0,2.0,10.0,0.0,0.0
1,Addison Town and Village,2577.0,3.0,0.0,0.0,0.0,3.0,24.0,3.0,20.0,1.0,0.0
2,Akron Village,2846.0,3.0,0.0,0.0,0.0,3.0,16.0,1.0,15.0,0.0,0.0
3,Albany,97956.0,791.0,8.0,30.0,227.0,526.0,4090.0,705.0,3243.0,142.0,NaN
4,Albion Village,6388.0,23.0,0.0,3.0,4.0,16.0,223.0,53.0,165.0,5.0,NaN

In [5]:
property_crime = pd.DataFrame()

property_crime['population'] = crime_df['Population']

property_crime['population_squared'] = property_crime['population']**2

property_crime['murder'] = np.where(crime_df['Murder and\nnonnegligent\nmanslaughter'] > 0, 1, 0)

property_crime['robbery'] = np.where(crime_df['Robbery'] > 0, 1, 0)

property_crime.head()

   population  population_squared  murder  robbery
0      1861.0        3.463321e+06       0        0
1      2577.0        6.640929e+06       0        0
2      2846.0        8.099716e+06       0        0
3     97956.0        9.595378e+09       1        1
4      6388.0        4.080654e+07       0        1